//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.03 at 02:45:33 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.atos.net/xml/pizzeria", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.atos.xml.pizzeria;
